### ISSUE TITLE
Failure at GenMCDriver.cpp:2017/visitMalloc()! with no malloc

### ISSUE THREAD

**Issue by db7** [MPI-SWS/genmc#32]
I keep getting this error (`BUG: Failure at GenMCDriver.cpp:2017/visitMalloc()!`) with LKMM in a piece of code that has no malloc calls calls. Do you have any suggestion how to figure out where this is happening in my code?

I tried `-disable-stop-on-system-error` but this seem to be an unrelated option.

**Comment by michaliskok** [comment]
The error pops up when GenMC encounters the allocation of an automatic variable, but it is not necessarily related to such an event.  Such a message would normally trigger during the report of an error to the user and/or due to some non-determinism in the code. 

Things you could try include:

1. Ensuring that the error is LKMM-specific. (Removing LKMM-specific fences and primitives is likely to make GenMC work with the code, even if there are `*_ONCE()` macros.)
2. Disabling Persevere (i.e., removing system calls altogether), in case you are using it.
3. Ensuring that there are no obvious out-of-bounds accesses or uninitialized automatic variables. (GenMC should catch these errors, but just in case...)

That said, this could also be a more serious bug in GenMC, but I cannot tell without the test case.

**Comment by db7** [comment]
Thanks for the tips. I did some further experiments.

1. It is related to LKMM, see below.
2. I'm not using persevere, and there are no syscalls.
3. I did a visual check of that, but couldn't find any issue out-of-bounds accesses. Since the same code works with IMM, I guess this is not the problem.

----

Following your suggestion, I replaced the LKMM with a "mock version" implementing the same interface but using stdatomic. Of course, the mapping of barriers won't be 100% the same, but I guess it is sufficient for answering this question.

Here is the output with LKMM:
```
user@bacad7635d0c:~$ genmc $OPTIONS -lkmm -- -Iinclude -DNTHREADS=4 client-code.c
WARNING: LKMM support is still at an experimental stage!
BUG: Failure at GenMCDriver.cpp:2017/visitMalloc()!
```

And there the output with IMM (using the mock LKMM atomics):
```
user@bacad7635d0c:~$ genmc $OPTIONS -imm -- -Iinclude -DNTHREADS=4 -DMOCK_LKMM client-code.c
Number of complete executions explored: 17568
Number of blocked executions seen: 123160
Total wall-clock time: 71.95s
```

Here are the other options passed to both cases: 
```
OPTIONS="-mo -print-error-trace -disable-bam -disable-stop-on-system-error -disable-race-detection -disable-load-annotation -disable-cast-elimination -disable-code-condenser -disable-spin-assume"
```

------
Also note that LKMM and IMM seem to have somehow a significant difference in performance. With 3 threads, both versions terminate.

With LKMM:
```
user@bacad7635d0c:~$ genmc $OPTIONS -lkmm -- -Iinclude -DNTHREADS=3 client-code.c
WARNING: LKMM support is still at an experimental stage!
Number of complete executions explored: 3295
Number of blocked executions seen: 8748
Total wall-clock time: 5.27s
```

With IMM:
```
user@bacad7635d0c:~$ genmc $OPTIONS -imm -- -Iinclude -DNTHREADS=3 -DMOCK_LKMM client-code.c
Number of complete executions explored: 364
Number of blocked executions seen: 1648
Total wall-clock time: 0.90s
```

**Comment by db7** [comment]
This problem seem to have disappeared in GenMC 0.7. Perhaps it wasn't related to malloc afterall but rather to #31.
